import { splitProps, type JSX } from "solid-js"
import { cn } from "@/lib/utils"
function Avatar(props: JSX.HTMLAttributes<HTMLSpanElement> & { size?: "default" | "sm" | "lg" }) { const [l,r]=splitProps(props,["class","size"]); const size=l.size||"default"; return <span data-slot="avatar" data-size={size} class={cn("group/avatar relative flex size-8 shrink-0 overflow-hidden rounded-full border border-border bg-card select-none data-[size=lg]:size-10 data-[size=sm]:size-6",l.class)} {...r}/> }
function AvatarImage(props: JSX.ImgHTMLAttributes<HTMLImageElement>) { const [l,r]=splitProps(props,["class"]); return <img data-slot="avatar-image" class={cn("aspect-square size-full",l.class)} {...r}/> }
function AvatarFallback(props: JSX.HTMLAttributes<HTMLSpanElement>) { const [l,r]=splitProps(props,["class"]); return <span data-slot="avatar-fallback" class={cn("flex size-full items-center justify-center rounded-full bg-primary/10 text-sm font-medium text-primary group-data-[size=sm]/avatar:text-xs",l.class)} {...r}/> }
function AvatarBadge(props: JSX.HTMLAttributes<HTMLSpanElement>) { const [l,r]=splitProps(props,["class"]); return <span data-slot="avatar-badge" class={cn("absolute right-0 bottom-0 z-10 inline-flex items-center justify-center rounded-full bg-primary text-primary-foreground ring-2 ring-background group-data-[size=lg]/avatar:size-3 group-data-[size=default]/avatar:size-2.5 group-data-[size=sm]/avatar:size-2",l.class)} {...r}/> }
function AvatarGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="avatar-group" class={cn("group/avatar-group flex -space-x-2 *:data-[slot=avatar]:ring-2 *:data-[slot=avatar]:ring-background",l.class)} {...r}/> }
function AvatarGroupCount(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="avatar-group-count" class={cn("relative flex size-8 shrink-0 items-center justify-center rounded-full border border-primary/20 bg-primary/10 text-sm font-medium text-primary ring-2 ring-background group-has-data-[size=lg]/avatar-group:size-10 group-has-data-[size=sm]/avatar-group:size-6 [&>svg]:size-4 group-has-data-[size=lg]/avatar-group:[&>svg]:size-5 group-has-data-[size=sm]/avatar-group:[&>svg]:size-3",l.class)} {...r}/> }
const AvatarCount = AvatarGroupCount
export { Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup, AvatarGroupCount, AvatarCount }
