import { createMemo, splitProps, type JSX } from "solid-js"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
function FieldSet(props: JSX.FieldsetHTMLAttributes<HTMLFieldSetElement>) { const [l,r]=splitProps(props,["class"]); return <fieldset data-slot="field-set" class={cn("flex flex-col gap-6 has-[>[data-slot=checkbox-group]]:gap-3 has-[>[data-slot=radio-group]]:gap-3",l.class)} {...r}/> }
function FieldLegend(props: JSX.HTMLAttributes<HTMLLegendElement> & { variant?: "legend" | "label" }) { const [l,r]=splitProps(props,["class","variant"]); return <legend data-slot="field-legend" data-variant={l.variant||"legend"} class={cn("mb-3 font-semibold data-[variant=label]:text-sm data-[variant=legend]:text-base",l.class)} {...r}/> }
function FieldGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="field-group" class={cn("group/field-group @container/field-group flex w-full flex-col gap-7 data-[slot=checkbox-group]:gap-3 [&>[data-slot=field-group]]:gap-4",l.class)} {...r}/> }
const fieldVariants = cva("group/field flex w-full gap-3 data-[invalid=true]:text-destructive", { variants: { orientation: { vertical: "flex-col [&>*]:w-full [&>.sr-only]:w-auto", horizontal: "flex-row items-center has-[>[data-slot=field-content]]:items-start [&>[data-slot=field-label]]:flex-auto has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px", responsive: "flex-col @md/field-group:flex-row @md/field-group:items-center [&>*]:w-full @md/field-group:[&>*]:w-auto [&>.sr-only]:w-auto @md/field-group:[&>[data-slot=field-label]]:flex-auto @md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px" } }, defaultVariants: { orientation: "vertical" } })
function Field(props: JSX.HTMLAttributes<HTMLDivElement> & VariantProps<typeof fieldVariants>) { const [l,r]=splitProps(props,["class","orientation"]); return <div role="group" data-slot="field" data-orientation={l.orientation||"vertical"} class={cn(fieldVariants({orientation:l.orientation}),l.class)} {...r}/> }
function FieldContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="field-content" class={cn("group/field-content flex flex-1 flex-col gap-1.5 leading-snug",l.class)} {...r}/> }
function FieldLabel(props: Parameters<typeof Label>[0]) { const [l,r]=splitProps(props,["class"]); return <Label data-slot="field-label" class={cn("group/field-label peer/field-label flex w-fit gap-2 leading-snug group-data-[disabled=true]/field:opacity-50 has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col has-[>[data-slot=field]]:rounded-md has-[>[data-slot=field]]:border [&>*]:data-[slot=field]:p-4 has-data-[state=checked]:border-primary has-data-[state=checked]:bg-primary/10",l.class)} {...r}/> }
function FieldTitle(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="field-label" class={cn("flex w-fit items-center gap-2 text-sm leading-snug font-semibold group-data-[disabled=true]/field:opacity-50",l.class)} {...r}/> }
function FieldDescription(props: JSX.HTMLAttributes<HTMLParagraphElement>) { const [l,r]=splitProps(props,["class"]); return <p data-slot="field-description" class={cn("text-sm leading-normal font-normal text-muted-foreground group-has-[[data-orientation=horizontal]]/field:text-balance last:mt-0 nth-last-2:-mt-1 [[data-variant=legend]+&]:-mt-1.5 [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",l.class)} {...r}/> }
function FieldSeparator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class","children"]); return <div data-slot="field-separator" data-content={!!l.children} class={cn("relative -my-2 h-5 text-sm",l.class)} {...r}><Separator class="absolute inset-0 top-1/2" />{l.children && <span class="relative mx-auto block w-fit bg-background px-2 text-muted-foreground" data-slot="field-separator-content">{l.children}</span>}</div> }
function FieldError(props: JSX.HTMLAttributes<HTMLDivElement> & { errors?: Array<{ message?: string } | undefined> }) { const [l,r]=splitProps(props,["class","children","errors"]); const content=createMemo(() => l.children || l.errors?.map(e=>e?.message).filter(Boolean).join(", ")); return content() ? <div role="alert" data-slot="field-error" class={cn("text-sm font-normal text-destructive",l.class)} {...r}>{content()}</div> : null }
export { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSeparator, FieldSet, FieldTitle }
